[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Geoffrey Royer", email = "geoffrey.royer@rhodatech.org"},
]
license = {text = "MIT"}
dependencies = [
    "flask>=3.1.2",
]
requires-python = ">=3.10"
